name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
